---
- name: Stop AppArmor service.
  systemd:
    name: apparmor
    state: stopped
  ignore_errors: true

- name: Remove AppArmor in update-rc.local .
  shell: update-rc.d -f apparmor remove
  ignore_errors: true

- name: Uninstall AppArmor .
  apt:
    name: apparmor
    state: absent
  ignore_errors: true


