---
- name: restart server
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} search_regex=OpenSSH port={{ ansible_port }} timeout=300 delay=60
